### PR TITLE
add constexpr to all function

### PR DESCRIPTION
**Pull request by schaumb**
After this, the named parameters can be used in constexpr evaluated context

### CODE REVIEW

**Comment by bluescarni** [comment]
@schaumb Thanks! Does the conflict resolution look ok to you?

**Comment by schaumb** [comment]
Yes, thanks!

**Comment by bluescarni** [comment]
Cheers!

**Comment by schaumb** [comment]
Oh no! We missed the template parameter! :( 

`template <::std::size_t I, typename Tag, typename ExplicitType>`

and
`template <typename... Tags, typename... ExplicitTypes>`

**Comment by bluescarni** [comment]
Should be fixed now.

**Comment by bluescarni** [comment]
@schaumb actually I think I screwed up the correction the first time. Can you please take a look at the last 2 commits on master? It should be ok now (I hope).

**Comment by schaumb** [comment]
It's OK now, thanks!

**Pull request merged**
